version: '3.5'

x-project-mount:
  &project-mount
  type: bind
  source: ./php/ci
  target: /var/www

services:
  php:
    build: ./php/
    volumes: 
      - *project-mount
    links:
      - mysql
      - redis
  mysql:
    image: mysql:5.7.23
    ports:
      - "3333:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  redis:
    image: redis
  nginx:
    build: ./nginx/
    restart: always
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - *project-mount
    links:
      - php